# Generated by Django 3.1 on 2022-08-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorialTitle', models.CharField(max_length=200)),
                ('tutorialContent', models.TextField(verbose_name='')),
                ('tutorialPublished', models.DateTimeField(verbose_name='date published ')),
            ],
        ),
    ]
