# Generated by Django 3.1 on 2022-08-25 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220825_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorialPublished',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 16, 1, 17, 234168), verbose_name='date published'),
        ),
    ]
